ALTER TABLE cases
    DROP CONSTRAINT IF EXISTS cases_status_check;

ALTER TABLE cases
    ADD CONSTRAINT cases_status_check
    CHECK (status IN ('FILED','ACTIVE','HEARING_SCHEDULED','ADJOURNED','DISPOSED'));